premieroctet/digestclub

src/components/Input.tsx
src/components/bookmark/BookmarksControls.tsx
src/components/pages/Team.tsx

**Issue**
https://github.com/premieroctet/digestclub/issues/4
**Screenshot**
Mobile
Desktop
Checked state

Bookmarks list switch

---

prisma/json-schema/json-schema.json
prisma/migrations/20230912152515_add_featured_flag/migration.sql
prisma/schema.prisma
src/components/home/HomeDigests.tsx
src/components/pages/Homepage.tsx
src/components/pages/TeamPublicPage.tsx
src/components/teams/PublicDigestCard.tsx
src/pages/admin/[[...nextadmin]].tsx

- Showcase featured digest on home

feat: add community digest on homepage

---

src/components/digests/block-card/text-card/TextCard.tsx
src/components/digests/dialog/AddTextBlockDialog.tsx
src/components/digests/dialog/EditTextBlockDialog.tsx
src/pages/api/teams/[teamId]/digests/[digestId]/block/[blockId]/index.tsx

Hi 👋🏻,
To add the ability of editing text blocks, I quickly duplicated the `EditBookmarkCard` file and modified the `.../{digestId}/block/{blockId}` endpoint `PATCH` implementation. Adding an `onEditClick` prop to the `BlockTextCard` component to show the `Edit` button in the Block Menu Popover.
Didn't test intensively, but it should work fine 😄 
- Merge `AddTextBlockDialog` and `EditTextBlockDialog` into one component?
- Cleanup the `.../{digestId}/block/{blockId}` file to avoid nesting. Factorize `if-else` statement in functions?

Add text block edit functionality

---

src/app/(routes)/teams/[teamSlug]/digests/[digestId]/edit/page.tsx
src/app/(routes)/teams/[teamSlug]/page.tsx
src/app/providers.tsx
src/components/Input.tsx
src/components/Popover.tsx
src/components/Tooltip.tsx
src/components/bookmark/Bookmark.tsx
src/components/bookmark/BookmarkAddButton.tsx
src/components/bookmark/BookmarkItem.tsx
src/components/bookmark/BookmarkListDnd.tsx
src/components/bookmark/BookmarksListControls.tsx
src/components/bookmark/BookmarksTeamList.tsx
src/components/bookmark/NewsBookmark.tsx
src/components/pages/DigestEditPage.tsx
src/components/pages/Team.tsx
src/emails/templates/NewsletterEmail.tsx
src/lib/queries.ts
src/messages/en.ts
src/pages/api/bookmark/index.ts
src/pages/api/teams/[teamId]/bookmark/index.ts
src/utils/bookmark.ts

**Issue**
https://github.com/premieroctet/digestclub/issues/7
- Keep only 1 call for listing in Team (getTeamBookmarksNotInDigest was not required as getTeamBookmarks enabled args to get only bookmarks not in digests)
**Screenshot**
Delete button for link bookmarked several times by team users
Delete button for link bookmarked one time by team users
Links bookmarked several times we display a tooltip with names and date of users bookmarking actions
User cannot add several same link in same team several times

Trending bookmarks listing

---

src/utils/link/index.test.js
src/utils/link/index.ts

Twitter links were not functioning correctly when the domain name 'x' was used. I have updated the utility functions and included new tests to accommodate the 'x' domain name.

merge fix/update-twitter-link-utils-with-x-domain-name to main

---

src/components/digests/BlockListDnd.tsx
src/components/digests/PublicDigestList.tsx
src/components/digests/block-card/BlockCard.tsx
src/components/digests/block-card/bookmark-card/BookmarkCard.tsx
src/components/digests/block-card/text-card/TextCard.tsx

Closes #29 
- Reduce gaps between blocks
- Add margin-top to `<h1>` except when the `<h1>` is the first block and the first child of the page
- Slightly reduce line-height in all markdown blocks
- Reduce all headings margin-bottom

merge 29-make-the-public-digest-page-more-compact-and-easier-to-read into main

---

src/components/pages/DigestEditPage.tsx
src/emails/templates/NewsletterEmail.tsx
src/utils/newsletter/index.ts

Related: #17 
To test these changes:
- spin up a `MailDev`
- apply [my patch](https://gist.github.com/MrNossiom/d472a777ef8acc3e164e2adc4087e5d3)
- send the digest newsletter on your local dashboard.
Many things are not done yet:
- Choose the breakpoint width
- Apply styles to `Text` blocks (raw HTML) and change the default theme to have bigger `h1`, etc.
- How to display tweets that have `.style == TWEET_EMBED`
It looks like this:

feat: update the style of the newsletter to match the web version

---

src/components/digests/ActionsBlockPopover.tsx
src/components/digests/block-card/text-card/TextCard.tsx

**Issue**
https://github.com/premieroctet/digestclub/issues/33
- Fix text block without space overflowing in digest block list
- Fix issue of block text options icon smaller on markdown blocks
**Screenshot**

Fix issue in text block overflow

---

src/components/bookmark/BookmarkImage.tsx
src/components/digests/block-card/bookmark-card/BookmarkCard.tsx
src/utils/bookmark.ts
src/utils/link/index.ts
src/utils/url.ts

**Issue**
https://github.com/premieroctet/digestclub/issues/45
- prevent metadata loading when importing pdf file link in bookmarks
- custom icon for PDF files to better identify them
**Screenshot**

Fix PDF import and cover image

---

src/app/(routes)/[teamSlug]/page.tsx
src/app/(routes)/discover/page.tsx
src/app/(routes)/teams/[teamSlug]/page.tsx
src/components/home/HomeDigests.tsx
src/components/list/Pagination.tsx
src/components/pages/DigestEditPage.tsx
src/components/pages/Team.tsx
src/components/pages/TeamPublicPage.tsx
src/components/teams/PublicDigestCard.tsx
src/components/teams/PublicDigestListItem.tsx
src/lib/queries.ts
src/pages/admin/[[...nextadmin]].tsx

**Issue**
https://github.com/premieroctet/digestclub/issues/54
Pagination for digests lists
- dashboard
- team public page
- specify count names for lists instead of totalCount
**Screenshot**
Team Public page
Dashboard page

Pagination for digests on team page and dashboard page

---

prisma/json-schema/json-schema.json
prisma/migrations/20231003092620_add_digest_template/migration.sql
prisma/migrations/20231005083313_digestblock_istemplate/migration.sql
prisma/schema.prisma
src/app/(routes)/teams/[teamSlug]/digests/[digestId]/edit/page.tsx
src/app/(routes)/teams/[teamSlug]/page.tsx
src/app/(routes)/teams/[teamSlug]/settings/page.tsx
src/components/Button.tsx
src/components/digests/DigestCreateInput.tsx
src/components/digests/templates/CreateTemplateModal.tsx
src/components/digests/templates/SelectTemplateModal.tsx
src/components/digests/templates/TemplateEdit.tsx
src/components/digests/templates/TemplateItem.tsx
src/components/pages/DigestEditPage.tsx
src/components/pages/Team.tsx
src/components/teams/TeamSettings.tsx
src/components/teams/form/settings/SettingsForm.tsx
src/components/teams/form/settings/TeamIntegrations.tsx
src/components/teams/form/settings/TeamTemplates.tsx
src/lib/queries.ts
src/pages/api/teams/[teamId]/digests/[digestId]/block/index.tsx
src/pages/api/teams/[teamId]/digests/index.ts

**Issue**
https://github.com/premieroctet/digestclub/issues/43
Will save all markdown and text blocks into a template digest to reuse it for next digests
- template creation
- template edition
- template deletion
**ScreenShots**
Pick a template
Save a template from DigestEditPage
Manage your templates
Edit your template

Add template for digests

---

src/actions/delete-invitation.ts
src/actions/generate-api-key.ts
src/actions/update-team-info.ts
src/components/teams/settings-tabs/invitations/InvitationList.tsx

Right now we got a stale value in optimistic update when inviting a new member so the UI doesn't refresh, the invitation props data are good though.
See https://github.com/vercel/next.js/issues/57662

fix: optimistic update

---

src/pages/api/teams/[teamId]/digests/[digestId]/index.ts
src/utils/openai.ts
yarn.lock

This pull request addresses some unintended behavior in the digest prediction feature. The following changes have been made:
- Reordered the digest entries from the earliest to the latest before feeding them into the prompt.
- Explicitly set the temperature (to 0.5).
- Added a fallback when the AI can't find a logical sequence.
- Deleted the previously set prediction when deleting a published digest.
- Retrieve only the latest 5 digest titles. A bug was identified when users attempted to change their titles; the prompt failed to consider the new entries as they were a minority in the prompt. Ex: `["Hi 1, Hi 2,..., Hi 6, New Digest Title #001, New Digest Title #002]`. This update not only resolves the bug but also contributes to cost savings by preventing unnecessary retrieval of all …

fix(digest): digest title prediction

---

src/app/(routes)/[teamSlug]/page.tsx
src/utils/prisma.ts

Fix NotFound that wasn't triggered here: [should-return-404](https://digest.club/should-return-404)
Fix #74
**TLDR:** _It's not exactly our 'usual' not found pattern because `FindFirstOrThrow` allows us to correctly type the props of the components. So, we let Prisma throw the error._
I could have used the pattern we use elsewhere in the application, where we don't let Prisma throw the "not found' error
```tsx
const Page = async () => {
const user = await getCurrentUser();
if (!user) return notFound();
return (
<div>
<div className="flex flex-col space-y-6 content-stretch">
<Component user={user!} />
</div>
</div>
);
};
```
However, I would need to update the `getTeamBySlug` function, which is currently `db.team.findFirstOrThrow(...)` to `db.team.findFirst(...)`.
This would make all types …

Fix notFound error in team page

---

package.json
src/app/(routes)/teams/[teamSlug]/page.tsx
src/components/Card.tsx
src/components/bookmark/BookmarksListControls.tsx
src/components/charts/Charts.tsx
src/components/charts/ChartsServer.tsx
src/components/charts/ChartsSkeleton.tsx
src/components/charts/ChartsTooltip.tsx
src/components/charts/Tooltip.tsx
src/components/digests/Digests.tsx
src/components/digests/templates/SelectTemplateModal.tsx
src/components/pages/Team.tsx
src/lib/queries.ts
yarn.lock

This pull request adds a graphical interface to the team's dashboard page, displaying graphs and charts that count and group all bookmarks per month. This enhancement enables users to visualize their team's contributions over time.
Fix #64 
I utilized Raw SQL since Prisma currently lacks support for grouping by date ranges or formatting dates directly within a `groupBy`. Additionally, I lowered the "level" in the React Tree where client rendering takes place to enable server-side rendering of the chart. As a result, `src/components/pages/Team.tsx` is now server-side rendered.

feat(charts): Add Bookmarked link metrics in Team page

---

src/pages/api/bookmark/index.ts

The `req.body` was incorrectly typed; it is a JavaScript object, not a string. Therefore, there is no need to parse it.
Fixes #57

Fix(api): bookmark endpoint

---

.github/workflows/test.yml
src/app/robot.ts
src/app/sitemap.ts

Add sitemap to the app, following [official NextJS documentation](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap). 
[And robot.txt](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots)
Fix #75
From NextJS documentation:
_In the future, we will support multiple sitemaps and sitemap indexes._
Added `SKIP_SITEMAP_GENERATION` in the Github Action test workflow, so this workflow will not need access to the database

feat(seo): add sitemap

---

src/messages/en.ts
src/utils/bookmark.ts

Only allows pdf and text content type (website) as saved bookmark
Fix #49

Fix(bookmark): restrict bookmark links to pdf and text only

---

src/components/pages/DigestEditPage.tsx

I did not test but it works in the devtools editor.
With a sticky panel it's easier to drag & drop a link with we did scroll.

Make the right panel sticky to easy drag & drop

---

src/components/ActiveTeams.tsx
src/services/database/team.ts

Do not display teams with empty digest in the Discover section

fix: dont display teams with empty digest

---

src/app/(app)/layout.tsx
tailwind.config.js

Fix #127 
- Add font for the website -> **Mulish**
Other possible typefaces were Poppins, Roboto. However, I believe Mulish is the best compromise. It displays numbers in a classic way, is not too bold, and is quite gentle to read
Could work as well
Too bold

Fix: Add Font (Mulish)

---

src/emails/templates/NewsletterEmail.tsx
src/emails/theme.ts

Fix: Various newsletter improvements

---

src/components/Input.tsx

Checked state was internally managed instead of being controlled by parent
This was causing some sync issue in a page that as the same switch twice (ex: https://digest.club/teams/[teamSlug])
1) Go to https://digest.club/teams/[teamSlug]
2) Click on the top _View all bookmarks_ switch
3) The bottom _View all bookmarks_ switch is not checked 
Now the switch is a controlled component

Fix switch input
