premieroctet/digestclub

src/components/digests/AddTextBlockButton.tsx, src/components/digests/BlockListDnd.tsx, src/components/digests/block-card/bookmark-card/BookmarkCard.tsx, src/components/digests/block-card/text-card/TextCard.tsx
**Issue**
https://github.com/premieroctet/digestclub/issues/3
**Screenshot**
=> Insert a block displayed in DnD list

src/app/(routes)/invitations/[invitationId]/accept/page.tsx
Replace getCurrentUserOrRedirect by getCurrentUser to fix Invitation
=> Fix get currentUser

src/utils/link/index.ts
**Issue**
https://github.com/premieroctet/digestclub/issues/5
- show invalid link message for 400 / 500 errors and prevent bookmark creation
=> Fix invalid link identification

src/components/Input.tsx
**Issue**
https://github.com/premieroctet/digestclub/issues/4
=> Switch opacity

src/components/digests/PublicDigestList.tsx
**Issue**
https://github.com/premieroctet/digestclub/issues/28
=> Count bookmarks only

src/lib/queries.ts
**Issue**
https://github.com/premieroctet/digestclub/issues/36
=> Search by url

.eslintrc.json, .husky/pre-commit, package.json, src/components/digests/dialog/AddTextBlockDialog.tsx, src/components/teams/form/TeamAPIKey.tsx, src/emails/templates/NewsletterEmail.tsx, src/hooks/useAddAndRemoveBlockOnDigest.ts, src/middleware.ts, src/pages/api/bookmark-og.tsx, src/pages/api/bookmark/index.ts, src/pages/api/team-og.tsx, src/pages/api/teams/[teamId]/bookmark/index.ts, src/pages/api/teams/[teamId]/digests/[digestId]/newsletter.tsx, src/pages/api/teams/[teamId]/subscriptions/index.tsx, src/utils/bookmark.ts, yarn.lock
Noticed we had some logs remaining in code
- add husky pre comit hook
- logs will need to be officially declared as expected
Not sure if we should keep actual logs, just ignored them for no but will at least prevent forgotten logs in future code 🧹
=> Add husky pre commit and remove logs

src/components/digests/PublicDigestList.tsx, src/components/teams/PublicDigestCard.tsx, src/pages/api/teams/[teamId]/digests/[digestId]/index.ts, src/utils/date.ts
- Fix date issue
- Make OpenAI call optional
=> Fix date issue and make openai call optional

src/components/teams/form/settings/TeamColorField.tsx
=> Remove text in code

package.json, prisma/json-schema/json-schema.json, prisma/migrations/20231024154423_bookmark_summary/migration.sql, prisma/schema.prisma, src/components/Button.tsx, src/components/Input.tsx, src/components/digests/block-card/bookmark-card/BookmarkCard.tsx, src/components/digests/dialog/EditBookmarkDialog.tsx, src/components/digests/dialog/SummaryButton.tsx, src/components/teams/form/settings/SettingsField.tsx, src/components/teams/form/settings/SettingsForm.tsx, src/components/teams/form/settings/form-data.tsx, src/lib/middleware.ts, src/pages/api/teams/[teamId]/bookmark/summary.tsx, src/utils/bookmark.ts, yarn.lock
**Issue**
https://github.com/premieroctet/digestclub/issues/53
Add summary generation for bookmark in digests
**Screenshots**
Prompt in team settings
Summary generation button
=> Bookmark summary generation

src/components/digests/block-card/bookmark-card/card-style/Block.tsx, src/components/teams/TeamAvatar.tsx, src/components/teams/form/settings/SettingsForm.tsx, src/pages/api/teams/[teamId]/bookmark/summary.tsx, src/pages/api/teams/[teamId]/digests/[digestId]/index.ts, src/utils/openai.ts
- issue on no initial color not displaying properly avatar for team in settings
- making openAi model selectable
- fix issue with title padding on bookmark blocks in digest edition
- fix default value for prompt in team settings
=> Optional OpenAi model and small fixes

src/components/digests/Digests.tsx
- Add publication date for digests listing in Dashboard
=> Published digest date in team listing

src/components/teams/form/settings/SettingsField.tsx, src/components/teams/form/settings/form-data.tsx, src/pages/api/teams/[teamId]/bookmark/summary.tsx
- better error mgmt for summary generation
- limit to prompt size
- limit to customised prompt in team settings
=> Better error handling in openAi + limit to prompt length

src/components/pages/DigestEditTypefully.tsx, src/messages/en.ts
Hey :wave:,
This PR will fix :
1 typo in `src/components/pages/DigestEditTypefully.tsx`
5 typos in `src/messages/en.ts`
Best!
=> docs: fix typos

.github/workflows/test.yml, package.json, prisma/json-schema/json-schema.json, prisma/migrations/20231102150640_digest_views/migration.sql, prisma/schema.prisma, src/app/(routes)/[teamSlug]/[digestSlug]/page.tsx, src/components/digests/Digests.tsx, src/components/digests/block-card/bookmark-card/BookmarkCard.tsx, src/components/digests/block-card/bookmark-card/card-style/Block.tsx, src/components/digests/block-card/bookmark-card/card-style/Inline.tsx, src/lib/queries.ts, yarn.lock
Also updated Next.js from 13.5 => 14.
| Team home | Edit digest |
|--------|--------|
| ![image](https://github.com/premieroctet/digestclub/assets/686101/9ed49f0b-ccf7-4c29-b1c8-547b5faad858) | ![image](https://github.com/premieroctet/digestclub/assets/686101/2a6aa104-2594-4c0a-bd59-19ebfa1f92fd) |
=> feat(#67): add statistics on links and digests

package.json, src/app/(routes)/teams/[teamSlug]/layout.tsx, src/components/account/AccountForm.tsx, src/components/buttons/SubmitButton.tsx, src/components/pages/Homepage.tsx, src/components/teams/form/TeamAPIKey.tsx, src/components/teams/form/settings/SettingsForm.tsx, src/components/teams/settings-tabs/invitations/InvitationList.tsx, yarn.lock
After [upgrading to Next 14](https://github.com/premieroctet/digestclub/pull/68), some imports are now invalid
=> fix: react imports

src/emails/templates/NewsletterEmail.tsx
We now display title above the link button, for readability
=> Fix(newsletter): fix overflow text on link label

src/pages/api/bookmark/index.ts, src/pages/api/teams/[teamId]/bookmark/index.ts, src/pages/api/teams/[teamId]/key/new.tsx, src/pages/api/webhooks/slack/events.ts, src/pages/api/webhooks/slack/shortcuts.ts, src/services/database/bookmark.ts, src/services/database/digest-block.ts, src/services/database/link.ts, src/utils/bookmark.ts
- Add AI generation tags on "save bookmark" action.
- Copy bookmarks tags (via link) to digestBlock on creation
=> Feat(tags): [AI] Add tag on bookmark save

src/pages/api/bookmark/index.ts
Reorder imports and fix _bookmark_ POST endpoint (API)
=> Fix api bookmark

src/services/database/team.ts
It seems that the RSS is updated very late each time. This should fix the issue.
=> fix: digest team cache

src/components/home/HomeOpenSource.tsx, src/components/pages/Homepage.tsx
=> feat: add open-source section

package.json, src/middleware.ts, yarn.lock
see https://github.com/redirectionio/vercel-middleware
=> add redirection.io middleware

package.json, src/app/(app)/page.tsx, src/middleware.ts, src/pages/api/teams/[teamId]/bookmark/summary.tsx, src/services/database/link.ts, src/utils/openai.ts
- Switch to gpt-o model
- Fix issue with logged CTA on homepage
- Remove unused redirection middleware
=> feat: switch to gpt-o, fix some issue

src/app/(app)/(routes)/[teamSlug]/[digestSlug]/page.tsx
=> Fix: Preview metadata for LinkedIn

src/app/(app)/(routes)/tags/[slug]/page.tsx, src/components/layout/Logo.tsx
- Fix #124 
- Add different visual style in the header for local development
=> Fix: Bug pagination in tags 

src/components/digests/DigestCreateInput.tsx
=> Fix default team cookie

LICENSE
=> Fix: Create LICENSE

src/components/bookmark/BookmarkListDnd.tsx, src/services/database/link.ts
=> Fix: Prisma query for unused bookmarks

.github/workflows/code-check.yml
Add new workflow to PRs on `main`
- Warning on Prisma's migrations with a drop on a column or table
=> Feat: add new workflow
